language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements.txt

script:
  - pytest --cov=./
  - pycodestyle --max-line-length=80 --count --statistics .
  - pytype --config pytype.cfg
